/* ONE SHOT v6.1.1 · CONTEXT VOICE + RELATION HELP + REPORT UX */
window.addEventListener('load',()=>{try{
 if(typeof ONEAssistant==='undefined'||typeof State==='undefined')return;
 const $=id=>document.getElementById(id);
 const speak=(msg)=>{
   const text=String(msg||'').trim().slice(0,240); if(!text||State.settings.assistantVoice===false||!('speechSynthesis' in window))return;
   const editing=typeof GuidedEditor!=='undefined'&&GuidedEditor.sessionActive===true;
   if(editing){GuidedEditor.lastAssistantSpeech=text;GuidedEditor.lastAssistantSpeechAt=Date.now();GuidedEditor.speechLock=true;clearTimeout(GuidedEditor.resumeListenTimer);try{GuidedEditor.recognition?.abort?.()}catch(_){}GuidedEditor.recognition=null;GuidedEditor.robot('speaking');}
   try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='es-PE';u.rate=1.02;
     u.onend=u.onerror=()=>{if(editing){GuidedEditor.speechLock=false;if(GuidedEditor.listenRequested){GuidedEditor.robot('waiting');GuidedEditor.resumeListenTimer=setTimeout(()=>{if(GuidedEditor.sessionActive&&GuidedEditor.listenRequested&&!GuidedEditor.speechLock)GuidedEditor.listen();},620);}else GuidedEditor.robot('idle');}};
     speechSynthesis.speak(u);
   }catch(_){if(editing)GuidedEditor.speechLock=false;}
 };
 ONEAssistant.say=speak;
 if(!sessionStorage.getItem('oneCameraHelloV611')){sessionStorage.setItem('oneCameraHelloV611','1');setTimeout(()=>{if(ONEAssistant.currentView==='Camera'&&State.settings.assistantAuto!==false){ONEAssistant.setState('greeting','Cámara lista');ONEAssistant.nudge('Cámara lista. Toma tu evidencia; después te ayudo con historial y clasificación.','success',true);speak('Cámara lista. Cuando tomes una evidencia, revisaré contigo si pertenece a un lugar anterior o si es nueva.');}},1600);}
 const modal=$('relationModal'),sheet=modal?.querySelector('.relationSheet');
 if(sheet&&!$('relationHelpBtn')){
   const p=sheet.querySelector('p');
   const btn=document.createElement('button');btn.id='relationHelpBtn';btn.type='button';btn.className='relationHelpBtn';btn.innerHTML='🤖 <b>¿No sabes cuál elegir?</b><span>ONE te explica estas 4 opciones</span>';
   p?.insertAdjacentElement('afterend',btn);
   const help=document.createElement('div');help.id='relationHelpPanel';help.className='relationHelpPanel';help.hidden=true;help.innerHTML=`<div class="relationHelpHead"><div class="relationHelpBot"><i></i><i></i><b></b></div><div><b>ONE · Ayuda de historial</b><small>Elige según el mismo elemento físico, no solo por cercanía.</small></div><button id="relationHelpClose" type="button">×</button></div><div class="relationHelpSpeech">Si comparas con la evidencia anterior:</div><div class="relationHelpGrid"><button data-rel-help="Permanece"><b>✓ Permanece</b><span>Es el mismo elemento y sigue prácticamente igual.</span></button><button data-rel-help="Modificada"><b>↻ Modificada</b><span>Es el mismo elemento/punto, pero cambió el contenido.</span></button><button data-rel-help="Retirada"><b>× Retirada</b><span>El elemento anterior ya no está. La visita actual documenta su retiro.</span></button><button data-rel-help="Nueva"><b>＋ Nueva</b><span>Lo fotografiado es otro elemento distinto; se registra como evidencia independiente aunque esté cerca.</span></button></div><small class="relationHelpTip">Si todavía dudas, cierra esta ayuda y revisa la foto anterior. No se cambia nada hasta que elijas.</small>`;
   btn.insertAdjacentElement('afterend',help);
   btn.addEventListener('click',()=>{help.hidden=false;btn.hidden=true;speak('Te ayudo. Permanece es el mismo elemento sin cambio importante. Modificada es el mismo elemento con contenido cambiado. Retirada significa que ya no está. Nueva significa que fotografiaste otro elemento distinto.');});
   $('relationHelpClose')?.addEventListener('click',()=>{help.hidden=true;btn.hidden=false;});
   help.addEventListener('click',e=>{const b=e.target.closest('[data-rel-help]');if(!b)return;const k=b.dataset.relHelp;const txt={Permanece:'Permanece: usa esta opción si es el mismo elemento y sigue presente sin un cambio importante.',Modificada:'Modificada: es el mismo elemento o punto, pero su contenido cambió.',Retirada:'Retirada: el elemento que estaba antes ya no existe en el lugar.',Nueva:'Nueva: la evidencia actual corresponde a otro elemento distinto. Se guardará como punto independiente.'}[k];speak(txt);});
 }
 const style=document.createElement('style');style.dataset.oneV611='1';style.textContent=`
 .reportOneQuick{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;overflow:visible!important;gap:8px!important}.reportOneQuick button{white-space:normal!important;min-height:42px;text-align:center}.reportOnePartyRow{margin-top:2px}.reportOneCommand input{font-size:16px!important}.reportOneAssistant{overflow:hidden!important}.reportOneBody{overflow:hidden}.reportOneHealth{gap:8px!important}
 .relationHelpBtn{width:100%;margin:10px 0;border:1px solid #b8cef0;border-radius:16px;background:#eef5ff;color:#123c78;padding:12px 14px;display:grid;grid-template-columns:auto 1fr;column-gap:8px;text-align:left;align-items:center}.relationHelpBtn>b{font-size:13px}.relationHelpBtn>span{grid-column:2;font-size:10px;color:#607797}.relationHelpPanel{margin:10px 0 12px;padding:12px;border:1px solid #cfe0f7;border-radius:18px;background:linear-gradient(180deg,#f6faff,#edf5ff)}.relationHelpPanel[hidden]{display:none!important}.relationHelpHead{display:grid;grid-template-columns:42px 1fr auto;gap:9px;align-items:center}.relationHelpHead>div:nth-child(2){display:grid}.relationHelpHead small{font-size:9px;color:#61758e}.relationHelpHead>button{border:0;border-radius:10px;width:32px;height:32px;background:#e5eefb;color:#143f79}.relationHelpBot{position:relative;width:40px;height:34px;border:2px solid #4e9df4;border-radius:12px;background:#0b2e58}.relationHelpBot i{position:absolute;top:10px;width:6px;height:6px;border-radius:50%;background:#8fe8ff;animation:one611Blink 4s infinite}.relationHelpBot i:first-child{left:8px}.relationHelpBot i:nth-child(2){right:8px}.relationHelpBot b{position:absolute;left:50%;bottom:6px;width:14px;height:4px;border:2px solid #8bd2ff;border-top:0;border-radius:0 0 9px 9px;transform:translateX(-50%)}.relationHelpSpeech{margin:10px 0 7px;font-size:11px;color:#21466f}.relationHelpGrid{display:grid;grid-template-columns:1fr 1fr;gap:7px}.relationHelpGrid button{border:1px solid #d6e2f1;border-radius:13px;background:#fff;padding:10px;text-align:left;color:#173f72}.relationHelpGrid b{display:block;font-size:11px}.relationHelpGrid span{display:block;font-size:9px;color:#667990;margin-top:3px}.relationHelpTip{display:block;margin-top:9px;color:#6c7c91;font-size:9px;line-height:1.35}@keyframes one611Blink{0%,44%,100%{transform:scaleY(1)}46%,48%{transform:scaleY(.12)}}
 @media(max-width:420px){.reportOneQuick{grid-template-columns:1fr 1fr!important}.reportOneHealth{grid-template-columns:1fr 1fr!important}.relationHelpGrid{grid-template-columns:1fr}.reportOneAssistant{border-radius:18px!important}}
 `;document.head.appendChild(style);
 const fab=$('oneAssistantFab');
 if(fab){const fresh=fab.cloneNode(true);fab.replaceWith(fresh);fresh.addEventListener('click',()=>{if(ONEAssistant.currentView==='Reports'&&typeof ReportOne!=='undefined'){const card=$('reportOneAssistant');card?.classList.remove('minimized');card?.scrollIntoView({behavior:'smooth',block:'center'});ReportOne.render?.();ReportOne.say?.('Estoy aquí en Reportes. Puedes pedirme hoy, esta semana, solo listas, revisar observadas o preparar el Excel.','help',true);return;}ONEAssistant.open();});}
 if(typeof Reports!=='undefined'&&typeof Reports.makeExcel==='function'){
   try{let src=Reports.makeExcel.toString();if(src.includes('candidato,tipo:type')){src=src.replace('candidato,tipo:type','candidato:candidate,tipo:type');src=src.replace(/^async\s+makeExcel\s*\(\)\s*\{/,'async function(){');const fixed=(new Function('return ('+src+')'))();Reports.makeExcel=fixed;Reports.invalidate?.();}}
   catch(e){console.warn('No pude aplicar corrección candidato/candidate',e);}
 }
 if(typeof ReportOne!=='undefined'){
   const oldPrepare=ReportOne.prepare?.bind(ReportOne);if(oldPrepare)ReportOne.prepare=async()=>{try{return await oldPrepare();}catch(e){ReportOne.say(`No pude preparar el Excel: ${e?.message||e}. Revisa las evidencias observadas e intenta otra vez.`,'alert',true);}};
   const oldSay=ReportOne.say?.bind(ReportOne);if(oldSay)ReportOne.say=(t,s='speaking',voice=false)=>{oldSay(t,s,false);if(voice||['alert','success'].includes(s))speak(t);};
 }
}catch(e){console.warn('ONE SHOT v6.1.1 UX fix',e);}});
